sudo: required
services:
  - docker

before_install:
  - docker build -t guilhermesampaio/docker-react -f Dockerfile.dev .

script:
  - docker run guilhermesampaio/docker-react npm run test -- --coverage

